### ISSUE TITLE
Why does the program terminate when I use this interface?

### ISSUE THREAD

**Issue by mgooglegit** [ashleykleynhans/inswapper-flask-api#1]
when I use it in codespace,I got a logging,it cannot work
Successfully saved face swap source image: /tmp/inswapper/d56c4679-0a8d-4aee-bfc8-ccc53b953d4a.png
Saving face swap target image to disk: /tmp/inswapper/f11ab767-475f-49d0-8d9a-50e6f737ddc4.png
Successfully saved face swap target image: /tmp/inswapper/f11ab767-475f-49d0-8d9a-50e6f737ddc4.png
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./checkpoints/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./checkpoints/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./checkpoints/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./checkpoints/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: ./checkpoints/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (320, 320)
Terminated

**Comment by ashleykleynhans** [comment]
Looks like it ran out of system memory and was OOM killed.  How much system memory does the codespace have available?
