### ISSUE TITLE
Background near swapped face is broken

### ISSUE THREAD

**Issue by Vector-Gaming** [ashleykleynhans/inswapper-flask-api#2]
Hi

BACKGROUND_ENHANCE = True
FACE_RESTORE = True
FACE_UPSAMPLE = True
UPSCALE = 2
CODEFORMER_FIDELITY = 0.5

Background near face gets blurred and pixelated after the swap.

Is there any way to fix it?

**Source:**
![sm2](https://github.com/ashleykleynhans/inswapper-flask-api/assets/76566094/790e8249-fc0c-4c34-810c-a0ca3627e2c4)

**Target:**
![tm1](https://github.com/ashleykleynhans/inswapper-flask-api/assets/76566094/d764bd9f-8e6e-48b3-8992-b68e0e39a358)

**After swap:**
![broken](https://github.com/ashleykleynhans/inswapper-flask-api/assets/76566094/bb862a45-580b-49d3-a87f-1761a13379d5)

**Comment by ashleykleynhans** [comment]
Not sure, this is just an API layer for https://github.com/haofanwang/inswapper,  log an issue there instead.
